version: '3.8'

services:
  books-service:
    build: ./app  # path is relative to docker-compose-shorthand.yml location
    volumes:
      - type: bind
        source: ./app #host directory
        target: /app # container directory
    environment:
      # tells flask run to run in development mode and reload the code on change. This mode should only be used in development.
      FLASK_DEBUG: "true"
    ports:
      - "5001:80"  # host:container