#version: "3"

services:
  books-service:
    build:
      context: .
      dockerfile: BooksService/Dockerfile
    container_name: books-service
    ports:
      - "5001:80"
    volumes:
      - type: bind
        source: ./BooksService
        target: /app
    environment:
      MONGO_URI: mongodb://mongodb:27017/books
#      FLASK_DEBUG: "true"
    depends_on:
      - mongodb
    restart: always

  loans-service1:
    build:
      context: .
      dockerfile: LoansService/Dockerfile
    container_name: loans-service1
    ports:
      - "5002:80"
    volumes:
      - ./LoansService:/app
    environment:
      MONGO_URI: mongodb://mongodb:27017/loans
#      FLASK_DEBUG: "true"
    depends_on:
      - mongodb
    restart: always

  loans-service2:
    build:
      context: .
      dockerfile: LoansService/Dockerfile
    container_name: loans-service2
    ports:
      - "5003:80"
    volumes:
      - ./LoansService:/app
    environment:
      MONGO_URI: mongodb://mongodb:27017/loans
#      FLASK_DEBUG: "true"
    depends_on:
      - mongodb
    restart: always

  reverse:
      build: ./reverse
      ports:
        - "80:80"
      depends_on:
        - books-service
        - loans-service1
        - loans-service2
      container_name: reverse

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
